### ISSUE TITLE
Cannot launch game

### ISSUE THREAD

**Issue by Tabulika** [MHO-Revival/Docs#1]
Followed all [instructions](https://github.com/MHO-Revival/Docs/blob/main/Local%20server%20Installation%20Guide.md), but the game does not start. I tried to run mho_launcher.exe 15 times in a row. It does not work. I can not even imagine what the problem could be.

**Comment by GupyOh** [comment]
Hi, this week I tried to set this up, I did eveything as well, but like you, running mho_launcher.exe did not work. I eventually noticed that on the [Game.md](https://github.com/MHO-Revival/Docs/blob/main/Game.md) file the game is being called through MHOClient.exe, so I opened the cmd on the Bin32 path and tried opening it with the "-qos_id=123456789" argument used in the example, the game did open, but after the initial cutscene I couldn't Login because the "Characters were loading".

I'm just sharing this because maybe it will work for you, idk.

**Comment by yeom-young** [comment]
And now I have the same issue as your :D

**Comment by yeom-young** [comment]
So as far as I can know mho_launcher.exe tries to open MHOClient.exe but fails. 
![image](https://github.com/user-attachments/assets/c1ed217e-a8b4-42df-9352-23774a7acdb1)
After pressing Enter this cmd window closes and there's no 2nd cmd window.

**Comment by GupyOh** [comment]
Progress??
on mho_launcher.cpp I changed the "mho_dir" and "work_dir" to the "...\\\Bin32\\\\"(add the \\\ at the end!!) and "...\\\Monster Hunter Online\\\\" of my pc respectively, then I recompiled and swapped the files.

Now open an admin cmd, go to the Bin32 path and open mho_lancher.exe, tada, second cmd is now open, if you press Enter it will start something, if you have the server up it will connect to it, but eventually the second cmd will close and nothing will happen, there will be a process on Task Manager that I think is the Monster Hunter but still no game =(

![image](https://github.com/user-attachments/assets/3939a628-74c2-4fc0-aa8f-f0a1df365026)

**Comment by GupyOh** [comment]
YOOO, I closed everything I tried again and.......
![image](https://github.com/user-attachments/assets/79fccd99-1b68-4b89-b3c0-a96a72586585)
IT WORKED

**Comment by GupyOh** [comment]
I can't start a quest, might be skill issue tho

**Comment by yeom-young** [comment]
![image](https://github.com/user-attachments/assets/07aca998-d161-4d18-bcdb-29ff0d5b13a8)
YOOOOOOO
Dude you're my damn hero. Thx man <3

**Comment by yeom-young** [comment]
But... yeah... there're no npcs...

**Comment by GupyOh** [comment]
Yeah... no npc, no item box, no stamina, no weapon, something is wrong... Maybe something wrong with the db, idk, but I will keep looking.

**Comment by Estalions** [comment]
The server is incomplete it's impossible to do something other than moving around and if you have some skills you can change the map that can trigger some events like a dialog or an UI to open but that's all for now.
It needs more development for further or advanced features like that
